apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: prakharm1234/zomato-july:v1
        ports:
        - containerPort: 3000  # Port your application listens on
